### ISSUE TITLE
good job!  thanks

### ISSUE THREAD

**Issue by Allen15rg** [luoyetx/OrdinalRegression#2]
hello ,I also read the paper you refered, and I am also interested in deeplearning.
do you have some relative datas or networks for testing the modification.

Best wishes!

**Comment by ValentiaSulli** [comment]
Hi, thank you for your nice work! I have learned your ordinal regression loss layer and trained my model. But how can I test the model? Could you please contribute your test layer?
Any help would be highly appreciated.
Waiting for the reply.

**Comment by luoyetx** [comment]
@ValentiaSulli you can get the output of last layer (which gives ordinal regression loss layer the input), process the data out of network can be easily done. Some code like below.

```cpp
int age = 0;
for (int i = 0; i < 2*k; i += 2) {
  if (out[i] < out[i+1]) {
    age++;
  }
}
```

**Comment by ValentiaSulli** [comment]
@luoyetx Okay, I get it. Thank you very much!
Best wishes!
